server:
  port: 8081

spring:
  application:
    name: ef-server-user
  cloud:
    alibaba:
      seata:
        tx-service-group: wjs_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wjs123
    url: jdbc:mysql://localhost:3306/examfrog_cloud_user
    druid:
      initial-size: 5   # 连接池初始化大小
      min-idle: 10      # 最小空闲连接数
      max-active: 20    # 最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"     # 不统计这些请求数据
      stat-view-servlet: # 访问监控网页的登录用户名和密码
        enabled: true    # 新版默认值是 false, 需要手动打开
        login-username: root
        login-password: wjs123
        reset-enable: true
        allow: ""        # 允许所有ip访问


  redis:
    host: localhost
    port: 6379
    password: wjs123
    database: 0     # Redis数据库索引（默认为0）
    timeout: 300ms  # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjs.examfrog.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID              # 主键类型
      logic-delete-value: 1           # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0       # 逻辑未删除值(默认为 0)
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: false
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: true         # 二级缓存默认开启(Configuration 层)
    local-cache-scope: session  # 一级缓存(默认 session 层)



# 自定义 jwt 配置
jwt:
  tokenHeader: Authorization  # JWT存储的请求头
  tokenHead:
  secret: exam-frog-secret    # JWT加解密使用的密钥
  expiration: 604800          # JWT的超期限时间(默认 60*60*24*7 = 7天)


# 自定义 redis key
redis:
  databaseName: 'exam_frog'
  key:
    user: 'user'
    admin: 'admin'
    userRoleList: 'userRoleList'
    adminRoleList: 'adminRoleList'
    userResourcesList: 'userResourcesList'
    adminResourcesList: 'adminResourcesList'
    authCode: "portal:authCode:"
    hotList: "hotList"
    perDayHotList: "perDayHotList"
    hotListKeyIdx: "hotListKeyIdx"
  expire:
    default: 86400  # 24小时
    authCode: 120   # 验证码超期时间
  hotListSize: 3    # 存最近 x 天的热门(默认30)


# 自定义 id 生成器参数
hutool:
  idutil:
    workerId: 1
    datacenterId: 1


RBAC:
  defaultRoleId: 2
